#!/usr/bin/env python3
from pathlib import Path

def rw(path):
    p=Path(path); return p,p.read_text(encoding='utf-8')
def save(p,s): p.write_text(s,encoding='utf-8')
def rep(s,old,new,label):
    if new in s: return s
    if old not in s: raise SystemExit(f'{label}: anchor not found')
    return s.replace(old,new,1)

ROOT=Path('site')

# Module 1: persist the alignment evidence already used for ranking.
p,s=rw(ROOT/'assets/js/northern-module1-pinalflow-v1.js')
s=rep(s,"function careerSnapshot(o,origin){const op=opportunity(o),ic=interestConnection(o);return{","function careerSnapshot(o,origin){const op=opportunity(o),ic=interestConnection(o),dp=driverProfile(o),ia=alignment(o),oa=combinedAlignment(o);return{",'m1 snapshot setup')
s=rep(s," interestConnectionLabel:ic.label,\n regionalOpportunityLabel:op.label,"," interestConnectionLabel:ic.label,\n interestAlignmentScore:Number(ia.toFixed(1)),workDriverConnectionLabel:dp.label,workDriverAlignmentScore:dp.score==null?null:Number(dp.score.toFixed(1)),overallAlignmentScore:Number(oa.toFixed(1)),matchedWorkDrivers:(dp.matches||[]).map(x=>({key:x.key,label:x.label,score:Number(x.score.toFixed(1))})),alignmentModel:{label:'Overall Match',interestWeight:.60,workDriverWeight:.40,version:'northern-discover-alignment-v1'},\n regionalOpportunityLabel:op.label,",'m1 snapshot fields')
s=rep(s,"const shared=readShared();shared.module1={scores:scores||null,topInterests:top,selected:chosen,evidenceVersion:EVIDENCE_VERSION,geography:'Apache, Coconino, Gila & Navajo Counties, Arizona',updatedAt:now};","const activeDrivers=explicitDrivers(),driverBank=window.NORTHERN_ONET_DRIVERS;const scoredDrivers=activeDrivers.filter(key=>driverBank?.drivers?.[key]);const alignmentProfile={model:'60% O*NET interest alignment + 40% validated work-driver alignment',interestWeight:.60,workDriverWeight:.40,validatedWorkDrivers:activeDrivers.map(key=>({key,label:driverBank?.drivers?.[key]?.label||key})),scoredWorkDrivers:scoredDrivers.map(key=>({key,label:driverBank?.drivers?.[key]?.label||key})),note:'Stability, growth and participant-defined meaning remain separate evidence unless occupation-level O*NET evidence exists for that driver.',source:'BOOST Module 1 mindmap + O*NET occupation evidence',version:'northern-discover-alignment-v1'};const shared=readShared();shared.module1={scores:scores||null,topInterests:top,selected:chosen,alignmentProfile,evidenceVersion:EVIDENCE_VERSION,geography:'Apache, Coconino, Gila & Navajo Counties, Arizona',updatedAt:now};",'m1 shared alignment profile')
s=rep(s,"j.module1.careers=chosen;j.module1.evidenceVersion=EVIDENCE_VERSION;","j.module1.careers=chosen;j.module1.alignmentProfile=alignmentProfile;j.module1.evidenceVersion=EVIDENCE_VERSION;",'m1 journey alignment profile')
# Only enable work-driver sorting when at least one selected driver has O*NET occupation evidence.
s=s.replace("const hasDrivers=explicitDrivers().length>0;","const hasDrivers=explicitDrivers().some(k=>!!window.NORTHERN_ONET_DRIVERS?.drivers?.[k]);")
s=s.replace("if(mode==='drivers'&&!explicitDrivers().length)return;","if(mode==='drivers'&&!explicitDrivers().some(k=>!!window.NORTHERN_ONET_DRIVERS?.drivers?.[k]))return;")
s=s.replace("function driverProfile(o){const active=explicitDrivers(),bank=window.NORTHERN_ONET_DRIVERS,raw=bank?.occupations?.[String(o?.soc)]||null;","function driverProfile(o){const bank=window.NORTHERN_ONET_DRIVERS,raw=bank?.occupations?.[String(o?.soc)]||null,active=explicitDrivers().filter(k=>!!bank?.drivers?.[k]);")
save(p,s)

# Module 2: show Discover alignment and carry it into Reality Check records.
p,s=rw(ROOT/'assets/js/northern-module2-pinalflow-v1.js')
if 'function alignmentEvidence(o)' not in s:
    anchor='function prepHtml(o){'
    helper="""function alignmentEvidence(o){const matched=(o?.matchedWorkDrivers||[]).slice(0,3);return{overall:o?.overallAlignmentScore,interest:o?.interestAlignmentScore,drivers:o?.workDriverAlignmentScore,interestLabel:o?.interestConnectionLabel||'Interest evidence carried from Discover',driverLabel:o?.workDriverConnectionLabel||'Work-driver evidence carried from Discover',matched}}\nfunction scoreText(v){return Number.isFinite(Number(v))?Math.round(Number(v))+'%':'Not scored'}\nfunction alignmentHtml(o){const a=alignmentEvidence(o),profile=readJourney()?.module1?.alignmentProfile||readShared()?.module1?.alignmentProfile||{},validated=(profile.validatedWorkDrivers||[]).map(x=>x.label||x.key).filter(Boolean);return`<div class=\"intel\"><span class=\"badge prepBadge\">Discover alignment carried forward</span><h3>Why this career connected to you</h3><p>Reality Check does not re-score who you are. It carries the Discover evidence forward while you test the career against employers, wages, preparation and life fit.</p><div class=\"intelGrid\"><div class=\"intelCell\"><small>Overall Match</small><b>${scoreText(a.overall)}</b></div><div class=\"intelCell\"><small>O*NET interest alignment</small><b>${scoreText(a.interest)} • ${esc(a.interestLabel)}</b></div><div class=\"intelCell\"><small>Work-driver alignment</small><b>${scoreText(a.drivers)} • ${esc(a.driverLabel)}</b></div></div>${a.matched.length?`<div class=\"source\"><b>Strongest work-driver connections:</b> ${a.matched.map(x=>esc(x.label||x.key)).join(' • ')}</div>`:validated.length?`<div class=\"source\"><b>Your validated work drivers:</b> ${validated.slice(0,6).map(esc).join(' • ')}</div>`:''}<div class=\"source\">Overall Match is the Discover lens: 60% O*NET interests + 40% work drivers with occupation-level O*NET evidence. It supports exploration; it does not decide whether a career is right for you.</div></div>`}\n"""
    if anchor not in s: raise SystemExit('m2 helper anchor not found')
    s=s.replace(anchor,helper+anchor,1)
s=rep(s,'${prepHtml(o)}${researchHtml(o)}','${alignmentHtml(o)}${prepHtml(o)}${researchHtml(o)}','m2 alignment render')
s=rep(s," interestConnectionLabel:o.interestConnectionLabel||'',regionalOpportunityLabel:o.regionalOpportunityLabel||r.tier||'',passesRecommendationGate:"," interestConnectionLabel:o.interestConnectionLabel||'',interestAlignmentScore:o.interestAlignmentScore??null,workDriverConnectionLabel:o.workDriverConnectionLabel||'',workDriverAlignmentScore:o.workDriverAlignmentScore??null,overallAlignmentScore:o.overallAlignmentScore??null,matchedWorkDrivers:o.matchedWorkDrivers||[],alignmentModel:o.alignmentModel||null,regionalOpportunityLabel:o.regionalOpportunityLabel||r.tier||'',passesRecommendationGate:",'m2 record fields')
s=rep(s,"const shared=readShared();shared.module2={validationBySoc:validation,careers:records,topInterestThemes:themes,intelligenceVersion:EVIDENCE_VERSION,","const shared=readShared();const alignmentProfile=shared?.module1?.alignmentProfile||readJourney()?.module1?.alignmentProfile||null;shared.module2={validationBySoc:validation,careers:records,topInterestThemes:themes,alignmentProfile,intelligenceVersion:EVIDENCE_VERSION,",'m2 shared carry')
s=rep(s,"j.module2={...(j.module2||{}),validationBySoc:validation,careers:records,topInterestThemes:themes,intelligenceVersion:EVIDENCE_VERSION,","j.module2={...(j.module2||{}),validationBySoc:validation,careers:records,topInterestThemes:themes,alignmentProfile,intelligenceVersion:EVIDENCE_VERSION,",'m2 journey carry')
save(p,s)

# Module 3: display all three alignment lenses and save an alignment-by-SOC package.
p,s=rw(ROOT/'assets/js/northern-module3-gold-v1.js')
s=rep(s,"function saveModule3(m,complete=false){const s=readShared();s.module3={...(s.module3||{}),...(m||{}),updatedAt:new Date().toISOString()};","function saveModule3(m,complete=false){const s=readShared(),j0=readJourney(),m1=s?.module1||j0?.module1||{},list=m1.selected||m1.careers||[];const alignmentBySoc=Object.fromEntries((list||[]).filter(x=>x?.soc).map(x=>[String(x.soc),{overallAlignmentScore:x.overallAlignmentScore??null,interestAlignmentScore:x.interestAlignmentScore??null,workDriverAlignmentScore:x.workDriverAlignmentScore??null,interestConnectionLabel:x.interestConnectionLabel||'',workDriverConnectionLabel:x.workDriverConnectionLabel||'',matchedWorkDrivers:x.matchedWorkDrivers||[]} ]));s.module3={...(s.module3||{}),alignmentProfile:m1.alignmentProfile||s?.module2?.alignmentProfile||null,alignmentBySoc,...(m||{}),updatedAt:new Date().toISOString()};",'m3 save carry')
if 'function discoverAlignment(o)' not in s:
    anchor='function compareCard(d,o,s){'
    helper="function discoverAlignment(o){const z=m3()?.alignmentBySoc?.[String(o?.soc)]||o||{},fmt=v=>Number.isFinite(Number(v))?Math.round(Number(v))+'%':'Not scored';return{overall:fmt(z.overallAlignmentScore),interest:fmt(z.interestAlignmentScore),drivers:fmt(z.workDriverAlignmentScore),interestLabel:z.interestConnectionLabel||'Interest evidence carried from Discover',driverLabel:z.workDriverConnectionLabel||'Work-driver evidence carried from Discover',matched:z.matchedWorkDrivers||[]}}\n"
    if anchor not in s: raise SystemExit('m3 helper anchor not found')
    s=s.replace(anchor,helper+anchor,1)
s=rep(s,"function compareCard(d,o,s){const v=validationFor(o.soc),n=fullNorthern(o.soc)||o,l=lmiFor(n),a=skillAlignment(d,o,s),c=baseCareer(d,o),il=interestLabel(d,c),status=","function compareCard(d,o,s){const v=validationFor(o.soc),n=fullNorthern(o.soc)||o,l=lmiFor(n),a=skillAlignment(d,o,s),c=baseCareer(d,o),il=interestLabel(d,c),da=discoverAlignment(o),status=",'m3 compare setup')
s=rep(s,'<div class="boostM3Evidence"><span>Matches Your Interests</span><b>${esc(il)}</b></div><div class="boostM3Evidence"><span>Work preference evidence</span>','<div class="boostM3Evidence"><span>Overall Discover Match</span><b>${esc(da.overall)}</b></div><div class="boostM3Evidence"><span>O*NET interest alignment</span><b>${esc(da.interest)} • ${esc(da.interestLabel)}</b></div><div class="boostM3Evidence"><span>Work-driver alignment</span><b>${esc(da.drivers)} • ${esc(da.driverLabel)}</b>${da.matched.length?`<div class="boostM3Pills">${da.matched.slice(0,3).map(x=>`<span class="boostM3Pill">${esc(x.label||x.key)}</span>`).join(\'\')}</div>`:\'\'}</div><div class="boostM3Evidence"><span>Work preference evidence</span>','m3 compare alignment cards')
s=s.replace('Use my current experience, self-evaluated skills, O*NET interests, Workplace Skills Lab evidence, and Module 2 wage/life/preparation research','Use my current experience, self-evaluated skills, O*NET interests, validated Discover work drivers, Workplace Skills Lab evidence, and Module 2 wage/life/preparation research')
s=s.replace('<div class="boostM3Evidence"><span>Input</span><b>Your top O*NET interests</b></div>','<div class="boostM3Evidence"><span>Input</span><b>O*NET interests + Discover work drivers</b></div>')
save(p,s)

# Module 4: show Discover alignment and save it into the final evidence contract.
p,s=rw(ROOT/'module4-v4.html')
if 'function alignmentEvidence(c)' not in s:
    anchor='function regionalStory(c){'
    helper="function alignmentEvidence(c){const z=M3.alignmentBySoc?.[soc(c?.soc)]||c||{},fmt=v=>Number.isFinite(Number(v))?Math.round(Number(v))+'%':'Not scored';return{overall:fmt(z.overallAlignmentScore),interest:fmt(z.interestAlignmentScore),drivers:fmt(z.workDriverAlignmentScore),overallRaw:z.overallAlignmentScore??null,interestRaw:z.interestAlignmentScore??null,driversRaw:z.workDriverAlignmentScore??null,interestLabel:z.interestConnectionLabel||'Interest evidence carried from Discover',driverLabel:z.workDriverConnectionLabel||'Work-driver evidence carried from Discover',matched:z.matchedWorkDrivers||[],validated:(M1.alignmentProfile?.validatedWorkDrivers||M2.alignmentProfile?.validatedWorkDrivers||M3.alignmentProfile?.validatedWorkDrivers||[])}}\n"
    if anchor not in s: raise SystemExit('m4 helper anchor not found')
    s=s.replace(anchor,helper+anchor,1)
s=rep(s,'<br><small>${esc(interestStory(c))}</small></button>','<br><small>${(()=>{const a=alignmentEvidence(c);return `Overall ${esc(a.overall)} • Interests ${esc(a.interest)} • Work drivers ${esc(a.drivers)}`})()}</small></button>','m4 career card')
s=rep(s,"function renderSelected(){const c=selected();if(!c)return;const v=validation(c.soc),p=prep(c),m=mobilityStory(c),strengths=","function renderSelected(){const c=selected();if(!c)return;const v=validation(c.soc),p=prep(c),m=mobilityStory(c),a=alignmentEvidence(c),strengths=",'m4 selected setup')
s=rep(s,"const cards=[['INTEREST EVIDENCE',interestStory(c),''],['JOBS REALITY CHECK'","const cards=[['OVERALL DISCOVER MATCH',a.overall,''],['O*NET INTEREST ALIGNMENT',a.interest+' • '+a.interestLabel,''],['WORK-DRIVER ALIGNMENT',a.drivers+' • '+a.driverLabel,''],['JOBS REALITY CHECK'",'m4 evidence cards')
s=s.replace('Interest, Reality Check, transferable experience, Northern Arizona opportunity, preparation, and career pathway remain separate evidence.','Discover alignment (O*NET interests + your validated work drivers), Reality Check, transferable experience, Northern Arizona opportunity, preparation, and career pathway remain separate evidence.')
s=rep(s,"const c=selected(),v=validation(c.soc),m=mobilityStory(c),p=prep(c),l=lab(),route=","const c=selected(),v=validation(c.soc),m=mobilityStory(c),p=prep(c),al=alignmentEvidence(c),l=lab(),route=",'m4 result setup')
s=rep(s,"interestConnection:interestStory(c),topInterestThemes:topThemes(),jobs:","interestConnection:interestStory(c),interestAlignmentScore:al.interestRaw,workDriverConnection:al.driverLabel,workDriverAlignmentScore:al.driversRaw,overallAlignmentScore:al.overallRaw,matchedWorkDrivers:al.matched,validatedWorkDrivers:al.validated,alignmentModel:'60% O*NET interests + 40% validated work drivers',topInterestThemes:topThemes(),jobs:",'m4 result contract')
s=rep(s,'<p><b>Career:</b> ${esc(c.title)}</p><p><b>Career Mobility floor:</b>','<p><b>Career:</b> ${esc(c.title)}</p><p><b>Discover alignment:</b> Overall ${esc(al.overall)} • O*NET interests ${esc(al.interest)} • Work drivers ${esc(al.drivers)}</p><p><b>Career Mobility floor:</b>','m4 result detail')
save(p,s)

# Report helpers.
p,s=rw(ROOT/'assets/js/career-decision-report-v2-a.js')
if 'function alignmentEvidence()' not in s:
    s += "\nfunction alignmentEvidence(){const z=M3.alignmentBySoc?.[SOC]||C||{},fmt=v=>Number.isFinite(Number(v))?Math.round(Number(v))+'%':'Not scored';return{overall:fmt(B.overallAlignmentScore??z.overallAlignmentScore),interest:fmt(B.interestAlignmentScore??z.interestAlignmentScore),drivers:fmt(B.workDriverAlignmentScore??z.workDriverAlignmentScore),overallRaw:B.overallAlignmentScore??z.overallAlignmentScore??null,interestRaw:B.interestAlignmentScore??z.interestAlignmentScore??null,driversRaw:B.workDriverAlignmentScore??z.workDriverAlignmentScore??null,interestLabel:B.interestConnection||z.interestConnectionLabel||'Interest evidence carried from Discover',driverLabel:B.workDriverConnection||z.workDriverConnectionLabel||'Work-driver evidence carried from Discover',matched:B.matchedWorkDrivers||z.matchedWorkDrivers||[],validated:B.validatedWorkDrivers||M1.alignmentProfile?.validatedWorkDrivers||M2.alignmentProfile?.validatedWorkDrivers||M3.alignmentProfile?.validatedWorkDrivers||[]}}\nfunction mindmapProfile(){const m=M1.mindmap||J.module1?.mindmap||{},f=m.fields||{};return{dream:f.dreamJob||'',natural:f.dreamNatural||'',motivation:f.dreamMotivation||'',drivers:(alignmentEvidence().validated||[]).map(x=>typeof x==='string'?x:(x.label||x.key)).filter(Boolean)}}\n"
save(p,s)

p,s=rw(ROOT/'assets/js/career-decision-report-v2-b.js')
s=rep(s,"function supports(){const x=[],rl=B.regionalOpportunityLabel||C.regionalOpportunityLabel;","function supports(){const x=[],rl=B.regionalOpportunityLabel||C.regionalOpportunityLabel,al=alignmentEvidence();",'report supports setup')
s=rep(s,"if(B.interestConnection&&!/different/i.test(B.interestConnection))x.push(B.interestConnection);","if(B.interestConnection&&!/different/i.test(B.interestConnection))x.push(B.interestConnection);if(Number(al.driversRaw)>=55)x.push(`Work-driver alignment: ${al.drivers} • ${al.driverLabel}`);",'report supports driver')
s=rep(s,'<div class="section"><h2>What you learned about yourself</h2><div class="grid"><div class="card"><span class="label">STRONGEST INTEREST THEMES</span><b>${esc(themes().join(\' • \')||\'Not recorded\')}</b></div><div class="card"><span class="label">CAREER MOBILITY SIGNAL</span>','<div class="section"><h2>What you learned about yourself</h2>${(()=>{const m=mindmapProfile();return (m.dream||m.natural||m.motivation)?`<div class="intro"><b>Your Discover starting point</b><br>${m.dream?`Dream-work clue: ${esc(m.dream)}. `:\'\'}${m.natural?`What felt natural: ${esc(m.natural)}. `:\'\'}${m.motivation?`What mattered underneath it: ${esc(m.motivation)}.`:\'\'}</div>`:\'\'})()}<div class="grid"><div class="card"><span class="label">STRONGEST INTEREST THEMES</span><b>${esc(themes().join(\' • \')||\'Not recorded\')}</b></div><div class="card"><span class="label">OVERALL DISCOVER MATCH</span><b>${esc(alignmentEvidence().overall)}</b><span>60% O*NET interests + 40% validated work drivers</span></div><div class="card"><span class="label">O*NET INTEREST ALIGNMENT</span><b>${esc(alignmentEvidence().interest)}</b><span>${esc(alignmentEvidence().interestLabel)}</span></div><div class="card"><span class="label">WORK-DRIVER ALIGNMENT</span><b>${esc(alignmentEvidence().drivers)}</b><span>${esc(alignmentEvidence().driverLabel)}</span></div><div class="card"><span class="label">CAREER MOBILITY SIGNAL</span>','report participant alignment')
s=rep(s,'</div><div class="section"><span class="label">TRANSFERABLE STRENGTHS</span>${pills(strengths())}</div>','</div>${mindmapProfile().drivers.length?`<div class="section"><span class="label">VALIDATED WORK DRIVERS FROM DISCOVER</span>${pills(mindmapProfile().drivers)}</div>`:\'\'}${alignmentEvidence().matched.length?`<div class="section"><span class="label">STRONGEST WORK-DRIVER CONNECTIONS FOR THIS CAREER</span>${pills(alignmentEvidence().matched.slice(0,4).map(x=>typeof x===\'string\'?x:(x.label||x.key)))}</div>`:\'\'}<div class="section"><span class="label">TRANSFERABLE STRENGTHS</span>${pills(strengths())}</div>','report driver pills')
s=rep(s,'<div class="coachBox"><b>Interest themes</b><br>${esc(themes().join(\' • \')||\'Not recorded\')}</div><div class="coachBox"><b>Mobility signal</b>','<div class="coachBox"><b>Discover alignment</b><br>Overall: ${esc(alignmentEvidence().overall)} • O*NET interests: ${esc(alignmentEvidence().interest)} • Work drivers: ${esc(alignmentEvidence().drivers)}<br>${esc(alignmentEvidence().driverLabel)}${mindmapProfile().drivers.length?`<br>Validated drivers: ${esc(mindmapProfile().drivers.join(\' • \'))}`:\'\'}</div><div class="coachBox"><b>Interest themes</b><br>${esc(themes().join(\' • \')||\'Not recorded\')}</div><div class="coachBox"><b>Mobility signal</b>','report coach alignment')
save(p,s)

# Cache busts + Rosie endpoint version.
for path,repls in [
 (ROOT/'Northern_BOOST_Module1_PinalFlow_v1.html',[('northern-module1-pinalflow-v1.js?v=20260926sort1','northern-module1-pinalflow-v1.js?v=20260926align1')]),
 (ROOT/'Northern_BOOST_Module2_PinalFlow_v1.html',[('northern-module2-pinalflow-v1.js?v=20260911dbsync3','northern-module2-pinalflow-v1.js?v=20260926align1')]),
 (ROOT/'activity.html',[('northern-module3-gold-v1.js?v=20260910m3split5','northern-module3-gold-v1.js?v=20260926align1')]),
 (ROOT/'career-decision-report.html',[('career-decision-report-v2-a.js?v=20260910report4','career-decision-report-v2-a.js?v=20260926align1'),('career-decision-report-v2-b.js?v=20260910report4','career-decision-report-v2-b.js?v=20260926align1')]),
 (ROOT/'assets/js/boost-config.js',[('northern-ask-rosie-v1.js?v=20260913mapctx1','northern-ask-rosie-v1.js?v=20260926completion1')]),
 (ROOT/'assets/js/northern-ask-rosie-v1.js',[('boost-ask-rosie-northern-v171','boost-ask-rosie-northern-v172')]),
]:
    p,s=rw(path)
    for old,new in repls: s=s.replace(old,new)
    save(p,s)

print('Northern BOOST alignment carry-forward layer applied.')
